name: Audit

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '^1.18'

    - name: Install dependencies
      run: go mod tidy

    - name: Run tests
      run: go test -v ./...

    - name: Lint code
      run: |
        go install golang.org/x/lint/golint@latest
        golint ./...

    - name: Check formatting
      run: gofmt -l .